version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=master123
    ports:
      - 5432:5432
    volumes:
      - legate_api_db:/var/lib/postgresql/data
    networks:
      - legate_api

networks:
  legate_api:
    driver: bridge

volumes:
  legate_api_db:
    driver: local
